export const v2En = {
  caseStudy: 'Explore case study', overview: 'Project overview', close: 'Close details', problem: 'The product need', role: 'My contribution', solution: 'The implementation', architecture: 'Architecture at a glance', features: 'Product workflows', stack: 'Tools & responsibilities', result: 'What exists today', challenge: 'Technical challenges', decisions: 'Engineering decisions', lessons: 'Lessons learned', source: 'View code', live: 'Open application', similar: 'Have a similar project?', talk: 'Let’s discuss the details', preview: 'Project preview', evidence: 'Explore the application and source where available.', share: 'Copy project link', copied: 'Link copied', copyFailed: 'Copy the address from your browser to share this project.',
  engineering: { eyebrow: 'Beyond the interface', title: 'One product.', accent: 'Connected layers.', intro: 'How I approach a Vue.js + Node.js application: follow a user action from the interface to the data, then back to a clear response.', model: 'A working model · not a diagram of every project', hint: 'Select a layer to explore its responsibility.', auth: 'Authentication & permissions', authText: 'Check identity and access on the server; the interface is not a security boundary.', delivery: 'Deployment & debugging', deliveryText: 'Check configuration, reproduce failures, and trace requests across the interface, API, and database.', evidence: 'See these tools in my projects', layers: [
    { title: 'User interface', tech: 'Vue.js', icon: 'fa-brands fa-vuejs', brief: 'Components & state', detail: 'Reusable components turn a user’s action into a clear interface state, including loading, empty, and error states.', output: 'User action → request', code: 'submit → loading → result' },
    { title: 'API contract', tech: 'REST APIs', icon: 'fa-solid fa-plug', brief: 'Requests & responses', detail: 'A clear request shape and predictable responses keep the client and server connected without mixing their responsibilities.', output: 'Request → validated input', code: 'method + resource + response' },
    { title: 'Application logic', tech: 'Node.js / Express.js', icon: 'fa-solid fa-server', brief: 'Rules & validation', detail: 'Routes and middleware handle validation and coordinate server-side operations before returning an appropriate response.', output: 'Validated input → operation', code: 'route → middleware → handler' },
    { title: 'Relational data', tech: 'MySQL', icon: 'fa-solid fa-database', brief: 'Relationships & queries', detail: 'Tables and relationships describe the application’s data. Queries connect those records to the workflow the user needs.', output: 'Operation → data → response', code: 'tables + relations + queries' },
  ] },
  terminal: { open: 'Open developer terminal', title: 'Developer terminal', intro: 'A small command-line tour of my work. Choose a command or type below.', label: 'Command', run: 'Run command', help: 'Available commands: help, whoami, stack, projects, experience, contact, clear.', unknown: 'Command not found. Try help.', prompt: 'Try whoami', hint: 'Enter to run · ↑ ↓ history · Escape to close', empty: 'Terminal cleared. Ready for your next command.', egg: 'Full-stack mode activated. Follow the request, all the way to the data.', local: 'Local demo · no commands run on a server', visit: 'Explore projects', contact: 'Go to contact', experience: 'Read my experience' },
  rail: 'Tools I build with', pause: 'Pause technology rail', play: 'Resume technology rail', heroProof: '1+ year · 20+ projects · Vue.js + Node.js', engineeringLink: 'How I build systems',
};

export const v2Ar = {
  caseStudy: 'استكشف تفاصيل المشروع', overview: 'نظرة على المشروع', close: 'إغلاق التفاصيل', problem: 'احتياج المنتج', role: 'مساهمتي', solution: 'التنفيذ', architecture: 'نظرة على البنية', features: 'وظائف المنتج', stack: 'الأدوات ودورها', result: 'النتيجة الحالية', challenge: 'التحديات التقنية', decisions: 'قرارات التنفيذ', lessons: 'ما تعلمته', source: 'عرض الكود', live: 'فتح التطبيق', similar: 'لديك مشروع مشابه؟', talk: 'لنتحدث عن التفاصيل', preview: 'معاينة المشروع', evidence: 'استكشف التطبيق وكود المصدر حيثما يتوفران.', share: 'نسخ رابط المشروع', copied: 'تم نسخ الرابط', copyFailed: 'يمكنك نسخ عنوان الصفحة من المتصفح لمشاركة المشروع.',
  engineering: { eyebrow: 'ما وراء الواجهة', title: 'منتج واحد.', accent: 'طبقات مترابطة.', intro: 'هكذا أتعامل مع تطبيق Vue.js وNode.js: أتتبع إجراء المستخدم من الواجهة إلى البيانات، ثم إلى استجابة واضحة.', model: 'نموذج توضيحي · وليس مخططًا لكل مشروع', hint: 'اختر طبقة لاستكشاف دورها.', auth: 'المصادقة والصلاحيات', authText: 'التحقق من الهوية والصلاحيات يتم على الخادم؛ الواجهة وحدها لا تكفي لحماية البيانات.', delivery: 'النشر وتتبع المشكلات', deliveryText: 'مراجعة الإعدادات وإعادة إنتاج الأعطال وتتبع الطلب بين الواجهة وAPI وقاعدة البيانات.', evidence: 'شاهد هذه الأدوات في مشاريعي', layers: [
    { title: 'واجهة المستخدم', tech: 'Vue.js', icon: 'fa-brands fa-vuejs', brief: 'المكونات والحالة', detail: 'مكونات قابلة لإعادة الاستخدام تحوّل إجراء المستخدم إلى حالة واضحة، بما فيها التحميل والبيانات الفارغة والأخطاء.', output: 'إجراء المستخدم ← طلب', code: 'submit → loading → result' },
    { title: 'واجهة البرمجة', tech: 'REST APIs', icon: 'fa-solid fa-plug', brief: 'الطلبات والاستجابات', detail: 'صيغة واضحة للطلب واستجابات متوقعة تربطان الواجهة بالخادم مع الفصل بين مسؤولياتهما.', output: 'طلب ← مدخلات متحقق منها', code: 'method + resource + response' },
    { title: 'منطق التطبيق', tech: 'Node.js / Express.js', icon: 'fa-solid fa-server', brief: 'القواعد والتحقق', detail: 'المسارات وMiddleware تتحقق من المدخلات وتنسّق عمليات الخادم قبل إعادة الاستجابة المناسبة.', output: 'مدخلات صحيحة ← عملية', code: 'route → middleware → handler' },
    { title: 'البيانات العلائقية', tech: 'MySQL', icon: 'fa-solid fa-database', brief: 'العلاقات والاستعلامات', detail: 'الجداول والعلاقات تمثل بيانات التطبيق، والاستعلامات تربط السجلات بالوظيفة التي يحتاجها المستخدم.', output: 'عملية ← بيانات ← استجابة', code: 'tables + relations + queries' },
  ] },
  terminal: { open: 'افتح الطرفية التفاعلية', title: 'طرفية المطور', intro: 'جولة قصيرة في أعمالي عبر الأوامر. اختر أمرًا أو اكتبه بالأسفل.', label: 'الأمر', run: 'تنفيذ', help: 'الأوامر المتاحة: help, whoami, stack, projects, experience, contact, clear.', unknown: 'الأمر غير معروف. جرّب help.', prompt: 'جرّب whoami', hint: 'Enter للتنفيذ · ↑ ↓ للسجل · Escape للإغلاق', empty: 'تم مسح الطرفية. جاهز للأمر التالي.', egg: 'تم تفعيل وضع Full-Stack. تتبّع الطلب حتى يصل إلى البيانات.', local: 'تجربة محلية · لا تُنفّذ أوامر على الخادم', visit: 'استكشف المشاريع', contact: 'انتقل للتواصل', experience: 'اقرأ عن خبرتي' },
  rail: 'أدوات أستخدمها في البناء', pause: 'إيقاف شريط التقنيات', play: 'تشغيل شريط التقنيات', heroProof: '1+ سنة خبرة · 20+ مشروعًا · Vue.js + Node.js', engineeringLink: 'كيف أبني الأنظمة',
};
