export const v3En = {
  hero: { first: 'Kerolos', last: 'Morcos', signature: 'SIGNAL TO SYSTEM', statement: 'Interfaces. APIs. Data.', statementEnd: 'One complete system.', role: 'Full-Stack Developer', stack: 'Vue.js + Node.js', year: 'year of experience', projects: 'projects', scene: 'Explore the connected stack', sceneHint: 'Select a layer. Follow the connection.', portrait: 'The developer behind the system', ready: 'SYSTEM READY', pause: 'Pause Hero motion', resume: 'Resume Hero motion', layers: ['Interactive interfaces', 'A clear request contract', 'Express.js · application logic', 'Relational data, connected'], build: 'Built end to end', visit: 'Explore my work' },
  system: { label: 'System', title: 'Toggle System Mode', on: 'System Mode on', off: 'System Mode off', annotation: 'Engineering view · presentation overlay' },
  pointer: { view: 'VIEW', run: 'RUN', open: 'OPEN', visit: 'VISIT' },
  request: { title: 'Follow one request.', subtitle: 'From a click to the data—and back.', simulation: 'INTERACTIVE SIMULATION · NO LIVE REQUEST', run: 'Run request', again: 'Run again', running: 'Request in progress', idle: 'Ready when you are.', complete: '200 OK · Interface updated', reduced: 'Motion reduced · all stages resolved', steps: ['Vue component', 'REST API', 'Node / Express', 'MySQL query', 'JSON response', 'UI updated'], descriptions: ['A user asks for projects.', 'GET /api/projects', 'Validate input and apply access rules.', 'Read the requested records.', 'Return structured project data.', 'Render the result in the interface.'], evidence: 'Illustrative lifecycle—not a production performance measurement.' },
  terminal: { help: 'system [on|off] · goto projects|architecture · open mission-car-users · theme · status', done: 'Done.', invalid: 'Unknown destination or command. Type help.', status: 'Local portfolio interface · no backend health check', theme: 'Current palette', go: 'Opening the requested portfolio section.', project: 'Opening the project case study.' },
};
export const v3Ar = {
  hero: { first: 'كيرلس', last: 'مرقس', signature: 'SIGNAL TO SYSTEM', statement: 'واجهات. خدمات. بيانات.', statementEnd: 'نظام متكامل.', role: 'مطور Full-Stack', stack: 'Vue.js + Node.js', year: 'سنة خبرة', projects: 'مشروعًا', scene: 'استكشف طبقات التطبيق', sceneHint: 'اختر طبقة، وتتبع الاتصال.', portrait: 'المطور وراء النظام', ready: 'SYSTEM READY', pause: 'إيقاف حركة المقدمة', resume: 'تشغيل حركة المقدمة', layers: ['واجهات تفاعلية', 'عقد واضح للطلبات', 'Express.js · منطق التطبيق', 'بيانات مترابطة'], build: 'من الواجهة إلى البيانات', visit: 'استكشف أعمالي' },
  system: { label: 'النظام', title: 'تبديل وضع النظام', on: 'وضع النظام مفعّل', off: 'وضع النظام متوقف', annotation: 'عرض هندسي · طبقة توضيحية' },
  pointer: { view: 'عرض', run: 'تشغيل', open: 'فتح', visit: 'زيارة' },
  request: { title: 'تتبّع طلبًا واحدًا.', subtitle: 'من النقرة إلى البيانات، ثم إلى الواجهة.', simulation: 'محاكاة تفاعلية · لا يُرسل طلب فعلي', run: 'تشغيل الطلب', again: 'تشغيل مجددًا', running: 'الطلب قيد المحاكاة', idle: 'جاهز عندما تكون مستعدًا.', complete: '200 OK · تم تحديث الواجهة', reduced: 'حركة مخفّضة · اكتملت المراحل', steps: ['مكوّن Vue', 'REST API', 'Node / Express', 'استعلام MySQL', 'استجابة JSON', 'تحديث الواجهة'], descriptions: ['يطلب المستخدم عرض المشاريع.', 'GET /api/projects', 'التحقق من المدخلات وصلاحيات الوصول.', 'قراءة السجلات المطلوبة.', 'إرجاع بيانات المشاريع بصورة منظمة.', 'عرض النتيجة في واجهة التطبيق.'], evidence: 'دورة توضيحية للطلب، وليست قياسًا لأداء الإنتاج.' },
  terminal: { help: 'system [on|off] · goto projects|architecture · open mission-car-users · theme · status', done: 'تم.', invalid: 'وجهة أو أمر غير معروف. اكتب help.', status: 'واجهة المحفظة المحلية · ليست فحصًا لصحة الخادم', theme: 'لوحة الألوان الحالية', go: 'جارٍ فتح القسم المطلوب.', project: 'جارٍ فتح تفاصيل المشروع.' },
};
