<script setup>
defineProps({ isOpen: { type: Boolean, default: false }, lang: { type: String, required: true }, t: { type: Function, required: true }, themes: { type: Array, required: true }, themeName: { type: String, required: true }, font: { type: String, required: true } });
defineEmits(["close", "set-font", "set-theme", "reset"]);
const fontOptions = [{ id: "alexandria", name: "Alexandria", sample: "Alexandria" }, { id: "tajawal", name: "Tajawal", sample: "الخط الافتراضي" }, { id: "cairo", name: "Cairo", sample: "Cairo" }];
</script>

<template>
  <button id="settings-toggle" class="fixed top-1/2 right-0 w-12 h-12 bg-white/90 dark:bg-slate-900/90 backdrop-blur-md border-y border-l border-slate-200 dark:border-slate-700 rounded-l-xl flex items-center justify-center shadow-lg hover:bg-slate-50 dark:hover:bg-slate-800 text-slate-600 dark:text-slate-300 transition-all duration-300 group z-[70]" type="button" :aria-label="t('settings.customize')" :aria-expanded="isOpen" aria-controls="settings-sidebar" @click="$emit('close', !isOpen)"><i class="fa-solid fa-gear text-xl group-hover:rotate-90 transition-transform duration-500" aria-hidden="true"></i></button>
  <aside id="settings-sidebar" class="fixed top-0 right-0 h-full w-80 bg-white/95 dark:bg-slate-900/95 backdrop-blur-xl shadow-2xl transform transition-transform duration-300 z-[60] border-l border-slate-200 dark:border-slate-800" :class="isOpen ? 'translate-x-0' : 'translate-x-full'" role="dialog" :aria-label="t('settings.customize')" :aria-hidden="!isOpen">
    <div class="h-full flex flex-col"><div class="p-6 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between"><h3 class="text-xl font-bold dark:text-white flex items-center gap-2"><i class="fa-solid fa-sliders text-primary" aria-hidden="true"></i>{{ t('settings.customize') }}</h3><button class="w-8 h-8 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center text-slate-400 hover:text-primary hover:bg-slate-200 dark:hover:bg-slate-700 transition-all" type="button" :aria-label="t('settings.close')" @click="$emit('close', false)"><i class="fa-solid fa-xmark" aria-hidden="true"></i></button></div>
      <div class="flex-1 overflow-y-auto p-6 space-y-8"><div><h4 class="text-sm font-bold text-slate-500 dark:text-slate-400 mb-4 uppercase tracking-wider flex items-center gap-2"><i class="fa-solid fa-font text-xs" aria-hidden="true"></i>{{ t('settings.font') }}</h4><div class="space-y-3" role="radiogroup" :aria-label="t('settings.fontChoice')"><button v-for="option in fontOptions" :key="option.id" :class="['w-full p-4 rounded-xl border hover:border-primary/50 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-all group relative overflow-hidden', lang === 'ar' ? 'text-right' : 'text-left', font === option.id ? 'active border-primary border-2 bg-slate-50 dark:bg-slate-800' : 'border-slate-200 dark:border-slate-700']" role="radio" :aria-checked="font === option.id" type="button" @click="$emit('set-font', option.id)"><span :class="[`font-${option.id}`]" class="block text-lg font-bold text-slate-800 dark:text-slate-200 group-hover:text-primary transition-colors mb-1">{{ option.name }}</span><span class="text-xs text-slate-400">{{ option.id === 'tajawal' ? t('settings.defaultFont') : option.sample }}</span><span v-if="font === option.id" class="settings-option-check absolute top-1/2 -translate-y-1/2 text-primary" aria-hidden="true"><i class="fa-solid fa-check-circle text-xl"></i></span></button></div></div><div class="h-px bg-slate-200 dark:bg-slate-800"></div><div><h4 class="text-sm font-bold text-slate-500 dark:text-slate-400 mb-4 uppercase tracking-wider flex items-center gap-2"><i class="fa-solid fa-palette text-xs" aria-hidden="true"></i>{{ t('settings.color') }}</h4><div class="grid grid-cols-4 gap-3" :aria-label="t('settings.colorChoice')"><button v-for="theme in themes" :key="theme.name" :title="theme.name" :aria-label="theme.name" :aria-pressed="themeName === theme.name" type="button" class="w-12 h-12 rounded-full cursor-pointer transition-transform hover:scale-110 border-2 border-slate-200 dark:border-slate-700 hover:border-primary shadow-sm" :class="themeName === theme.name ? 'ring-2 ring-primary ring-offset-2 ring-offset-white dark:ring-offset-slate-900' : ''" :style="{ background: `linear-gradient(135deg, ${theme.primary}, ${theme.secondary})` }" @click="$emit('set-theme', theme.name)"></button></div></div></div>
      <div class="p-6 border-t border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/50"><button type="button" class="w-full py-3 px-4 rounded-xl bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-400 font-bold hover:bg-red-500 hover:text-white dark:hover:bg-red-600 transition-all flex items-center justify-center gap-2" @click="$emit('reset')"><i class="fa-solid fa-rotate-right" aria-hidden="true"></i>{{ t('settings.reset') }}</button></div>
    </div>
  </aside>
</template>
